{% set version = "1.0.4" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-rafalib
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/rafalib_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/rafalib/rafalib_{{ version }}.tar.gz
  sha256: e0ad1a7a51e2a5c9583a0f6d01a7b300bdf44f62515af02afddac4f9acef4413

build:
  noarch: generic
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  host:
    - r-base
    - r-biocmanager
    - r-rcolorbrewer
  run:
    - r-base
    - r-biocmanager
    - r-rcolorbrewer

test:
  commands:
    - $R -e "library('rafalib')"           # [not win]
    - "\"%R%\" -e \"library('rafalib')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=rafalib
  license: Artistic-2.0
  summary: 'A series of shortcuts for routine tasks originally developed by Rafael A. Irizarry to facilitate data exploration. '
  license_family: OTHER
  license_file: {{ environ["PREFIX"] }}/lib/R/share/licenses/Artistic-2.0

extra:
  recipe-maintainers:
    - conda-forge/r
