appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: UM91OGkFhiPvJtxHq52hF/sZWFzDQ5NQ6PQzEZsNHDaKNn3Xz88/Nq5px9d6PENvCPwjAIz+8MG03H7x0NquRWkVaPzkajkaG43h+J/K9CjhCuW/PZBNxzrEWDSugCVadEUQyDrUZ52HWsT3ypuCzad4yapiOX7qSYTdc/F2ynHnMgs6n1Z5vBkTvcGWjbgTPIkJhav1RVSRkajfkXJZMjSmSmftOmlVPyzAPZlRHxA/qShvYQu3H92qFbvroI4l56aNY09IvMPy+BxhpBZnfJcJ7bIAMun9GwSlFAWb3qrus+S4p71BJgax0lTPXyRxDIwsTP0TSL0q5lASXqCmFM2Z80Z/f8gZf6qGB9TBOW3Qea6ZQCKQ5mXg5cIGwKa9cBiQYnKgs4Uj1fPzV1iUnah/PB7n0qBYFnM+hGPQRUnWgO8IFAEY8a+RBZhvwIWVZF95HAyLMiP99kCi4J1XDlCg92QPJb0pWnsfJ6Dzj7eLGQFJTpeb0KLpNonNDgq+48mUWqtPcCM9b73WwdymZNcnLlCX9ZkmRhSecAf4rf+lAh29Vdtyh0OPmorZuvSEoQxU1fdz0DD3dcjqTI1pce5sMyY7U2DbWBvWoqA1DjMy4q0Ou4KAxn+TrumhPCnMR6huH8OxaP7xfhhkMi66mQaa1Ey51zr8wvYjmhAl2zQ=}
